In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl.metadata (19 kB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 2.7 MB/s eta 0:00:04
   ---------- ----------------------------- 2.6/9.9 MB 7.4 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 15.3 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 13.1 MB/s  0:00:01

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 164, in _make_candidate_from_dist
    base = self._installed_candidate_cache[dist.canonical_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\utils\logging.py", line 198, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 1697, in print
    with self:
         ^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 870, in __exit__
    self._exit_buffer()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 826, in _exit_buffer
    self._check_buffer()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 2038, in _check_buffer
    self._write_buffer()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 2074, in _write_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
    ~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\_win32_console.py", line 402, in write_text
    self.write(text)
    ~~~~~~~~~~^^^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 56-61: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Scripts\pip.exe\__main__.py", line 6, in <module>
    sys.exit(main())
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\main.py", line 80, in main
    return command.main(cmd_args)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\base_command.py", line 159, in main
    return self._main(args)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\base_command.py", line 238, in _main
    return self._run_wrapper(level_number, options, args)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\base_command.py", line 107, in _run_wrapper
    status = _inner_run()
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\base_command.py", line 98, in _inner_run
    return self.run(options, args)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\req_command.py", line 85, in wrapper
    return func(self, options, args)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\commands\install.py", line 388, in run
    requirement_set = resolver.resolve(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 99, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 601, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 513, in resolve
    failure_criterion = self._attempt_to_pin_criterion(name)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 220, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 211, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 125, in _add_to_criteria
    matches = self._p.find_matches(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 268, in find_matches
    return self._factory.find_candidates(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 450, in find_candidates
    return self._iter_found_candidates(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 341, in _iter_found_candidates
    _get_installed_candidate(),
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 289, in _get_installed_candidate
    candidate = self._make_candidate_from_dist(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 166, in _make_candidate_from_dist
    base = AlreadyInstalledCandidate(dist, template, factory=self)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 376, in __init__
    factory.preparer.prepare_installed_requirement(self._ireq, skip_reason)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\operations\prepare.py", line 737, in prepare_installed_requirement
    logger.info(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\logging\__init__.py", line 1520, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\logging\__init__.py", line 1665, in _log
    self.handle(record)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\logging\__init__.py", line 1681, in handle
    self.callHandlers(record)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\logging\__init__.py", line 1737, in callHandlers
    hdlr.handle(record)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\logging\__init__.py", line 1027, in handle
    self.emit(record)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\utils\logging.py", line 200, in emit
    self.handleError(record)
Message: 'Requirement %s: %s (%s)'
Arguments: ('already satisfied', <InstallRequirement object: numpy>=2.3.3 in c:\users\\u043d\u0443\u0440\u0430\u043b\u0438\appdata\local\programs\python\python314\lib\site-packages (from pandas) editable=False>, <Version('2.4.1')>)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 164, in _make_candidate_from_dist
    base = self._installed_candidate_cache[dist.canonical_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'python-dateutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\utils\logging.py", line 198, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 1697, in print
    with self:
         ^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 870, in __exit__
    self._exit_buffer()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 826, in _exit_buffer
    self._check_buffer()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 2038, in _check_buffer
    self._write_buffer()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 2074, in _write_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
    ~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\_win32_console.py", line 402, in write_text
    self.write(text)
    ~~~~~~~~~~^^^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 56-61: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Scripts\pip.exe\__main__.py", line 6, in <module>
    sys.exit(main())
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\main.py", line 80, in main
    return command.main(cmd_args)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\base_command.py", line 159, in main
    return self._main(args)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\base_command.py", line 238, in _main
    return self._run_wrapper(level_number, options, args)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\base_command.py", line 107, in _run_wrapper
    status = _inner_run()
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\base_command.py", line 98, in _inner_run
    return self.run(options, args)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\cli\req_command.py", line 85, in wrapper
    return func(self, options, args)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\commands\install.py", line 388, in run
    requirement_set = resolver.resolve(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 99, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 601, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 513, in resolve
    failure_criterion = self._attempt_to_pin_criterion(name)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 220, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 211, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 125, in _add_to_criteria
    matches = self._p.find_matches(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 268, in find_matches
    return self._factory.find_candidates(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 450, in find_candidates
    return self._iter_found_candidates(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 341, in _iter_found_candidates
    _get_installed_candidate(),
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 289, in _get_installed_candidate
    candidate = self._make_candidate_from_dist(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 166, in _make_candidate_from_dist
    base = AlreadyInstalledCandidate(dist, template, factory=self)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 376, in __init__
    factory.preparer.prepare_installed_requirement(self._ireq, skip_reason)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\operations\prepare.py", line 737, in prepare_installed_requirement
    logger.info(
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\logging\__init__.py", line 1520, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\logging\__init__.py", line 1665, in _log
    self.handle(record)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\logging\__init__.py", line 1681, in handle
    self.callHandlers(record)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\logging\__init__.py", line 1737, in callHandlers
    hdlr.handle(record)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\logging\__init__.py", line 1027, in handle
    self.emit(record)
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\utils\logging.py", line 200, in emit
    self.handleError(record)
Message: 'Requirement %s: %s (%s)'
Arguments: ('already satisfied', <InstallRequirement object: python-dateutil>=2.8.2 in c:\users\\u043d\u0443\u0440\u0430\u043b\u0438\appdata\local\programs\python\python314\lib\site-packages (from pandas) editable=False>, <Version('2.9.0.post0')>)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 164, in _make_candidate_from_dist
    base = self._installed_candidate_cache[dist.canonical_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_internal\utils\logging.py", line 198, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 1697, in print
    with self:
         ^^^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 870, in __exit__
    self._exit_buffer()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 826, in _exit_buffer
    self._check_buffer()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 2038, in _check_buffer
    self._write_buffer()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\\u041d\u0443\u0440\u0430\u043b\u0438\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\rich\console.py", line 2074, in _write_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In [2]:
import pandas as pd

In [3]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Evan"],
    "Age": [19, 21, 22, 20, 23],
    "Score": [85, 78, 92, 88, 75]
}

df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   19     85
1      Bob   21     78
2  Charlie   22     92
3    Diana   20     88
4     Evan   23     75

In [4]:
df.head(3)

df.describe()

df["Score"].mean()

np.float64(83.6)

In [5]:

df[df["Age"] > 20]

df[df["Score"] > 80]

      Name  Age  Score
0    Alice   19     85
2  Charlie   22     92
3    Diana   20     88